site_name: lair-postgis
site_url: https://milleniumbrasil.github.io/lair-postgis/
repo_name: milleniumbrasil/lair-postgis
repo_url: https://github.com/milleniumbrasil/lair-postgis
nav:
  - Início: index.md

theme:
  name: material

plugins:
  - search
  - versioning

extra_css:
  - css/extra.css

extra_javascript:
  - js/custom.js

markdown_extensions:
  - admonition
  - toc:
      permalink: true