CREATE DATABASE lair;
CREATE DATABASE sacir;

\connect sacir
CREATE ROLE sacir WITH SUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1 PASSWORD 'sacir';
CREATE SCHEMA sacir;
