version: "3.9"

services:
  # Serviço para execução em batch (não-interativo)
  notebook-runner:
    build:
      context: .
      dockerfile: NotebooksDockerfile
    volumes:
      - ./:/home/jovyan/work
      - ./input:/home/jovyan/data/input
      - ./output:/home/jovyan/data/output
    environment:
      # Variáveis globais
      - INPUT_PATH=/home/jovyan/data/input
      - OUTPUT_PATH=/home/jovyan/data/output
      - PYTHONUNBUFFERED=1
      
      # Variáveis para o notebook 01_Download_CAR_estados.ipynb
      - SICAR_REPO=https://github.com/urbanogilson/SICAR
      - SICAR_EMAIL=sicar@sicar.com
      - ESTADOS_CAR=AC,AM,PA,AP,TO,MA,PI,CE,RN,PB,PE,AL,SE,BA,MG,ES,RJ,SP,PR,SC,RS,MS,MT,GO,DF,RO,RR
      - CAR_FOLDER=CAR
      - DEBUG=False
      
      # Variáveis para o notebook 02_UsosABC.ipynb
      - ORIGINAIS_PATH=originais_path
      - LIMITES_BUF=limites_buf
      - MUNICIPIOS_PATH=Municipios
      - MUNICIPIOS_FILE=BR_Municipios_2021.shp
      - ANOS_ABC=1985,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
    command: python run_notebooks.py
    profiles:
      - batch

  # Serviço para execução interativa
  jupyter-interactive:
    build:
      context: .
      dockerfile: NotebooksDockerfile
    volumes:
      - ./:/home/jovyan/work
      - ./input:/home/jovyan/data/input
      - ./output:/home/jovyan/data/output
    environment:
      # Variáveis globais
      - INPUT_PATH=/home/jovyan/data/input
      - OUTPUT_PATH=/home/jovyan/data/output
      - PYTHONUNBUFFERED=1
      
      # Variáveis para o notebook 01_Download_CAR_estados.ipynb
      - SICAR_REPO=https://github.com/urbanogilson/SICAR
      - SICAR_EMAIL=sicar@sicar.com
      - ESTADOS_CAR=AC,AM,PA,AP,TO,MA,PI,CE,RN,PB,PE,AL,SE,BA,MG,ES,RJ,SP,PR,SC,RS,MS,MT,GO,DF,RO,RR
      - CAR_FOLDER=CAR
      - DEBUG=False
      
      # Variáveis para o notebook 02_UsosABC.ipynb
      - ORIGINAIS_PATH=originais_path
      - LIMITES_BUF=limites_buf
      - MUNICIPIOS_PATH=Municipios
      - MUNICIPIOS_FILE=BR_Municipios_2021.shp
      - ANOS_ABC=1985,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
    ports:
      - "8888:8888"
    command: jupyter notebook --ip=0.0.0.0 --allow-root --NotebookApp.token=''
    profiles:
      - interactive

# Para executar em modo batch:
# docker-compose -f NotebooksCompose.yaml --profile batch up

# Para executar em modo interativo:
# docker-compose -f NotebooksCompose.yaml --profile interactive up