version: "3.9"

services:
  # Serviço para execução em batch (não-interativo)
  notebook-runner:
    build:
      context: .
      dockerfile: NotebooksDockerfile
    volumes:
      - ./:/home/jovyan/work
      - ./input:/home/jovyan/data/input
      - ./output:/home/jovyan/data/output
    environment:
      # Variáveis globais
      - INPUT_PATH=/home/jovyan/data/input
      - OUTPUT_PATH=/home/jovyan/data/output
      - PYTHONUNBUFFERED=1
      
      # Variáveis para o notebook 01_Download_CAR_estados.ipynb
      - SICAR_REPO=https://github.com/urbanogilson/SICAR
      - SICAR_EMAIL=sicar@sicar.com
      - ESTADOS_CAR=AC,AM,PA,AP,TO,MA,PI,CE,RN,PB,PE,AL,SE,BA,MG,ES,RJ,SP,PR,SC,RS,MS,MT,GO,DF,RO,RR
      - CAR_FOLDER=CAR
      - DEBUG=False
      
      # Variáveis para o notebook 02_UsosABC.ipynb
      - ORIGINAIS_PATH=originais_path
      - LIMITES_BUF=limites_buf
      - MUNICIPIOS_PATH=Municipios
      - MUNICIPIOS_FILE=BR_Municipios_2021.shp
      - ANOS_ABC=1985,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
      
      # Variáveis para o notebook 03_Declividade.ipynb
      - DECLIV_PATH=originais_path
      - TEMP_FOLDER=Temporarios
      - DECLIV_OUTPUT=Decliv_UF_Municipios
      - DECLIV_CAR_OUTPUT=Decliv_UF_Municipios_CAR
      
      # Variáveis para o notebook 04_CorrecaoEdafo.ipynb
      - APTIDAO_PATH=originais_path
      - APTIDAO_OUTPUT=Aptidao_Solo_Corrigida
      
      # Variáveis para o notebook 05_AptdEdafo.ipynb
      - APTIDAO_CORRIGIDA_PATH=Aptidao_Solo_Corrigida
      - APTIDAO_MUN_OUTPUT=Aptd_Edafo_Municipios
      - APTIDAO_CAR_OUTPUT=Aptd_Edafo_Municipios_CAR
      
      # Variáveis para o notebook 06_TerraIndigena.ipynb
      - TI_FILE=tis_poligonais.shp
      - TI_ESTADOS_OUTPUT=Terras_Indigenas_Estados
      - TI_MUNICIPIOS_OUTPUT=Terras_Indigenas_Municipios
      
      # Variáveis para o notebook 07_AmazoniaLegal.ipynb
      - AMZ_FILE=amazonia_legal.shp
      - AMZ_ESTADOS_OUTPUT=Amz_Legal_Estados
      - AMZ_MUNICIPIOS_OUTPUT=Amz_Legal_Municipios
      
      # Variáveis para o notebook 08_FaixaFronteira.ipynb
      - FAIXA_PATH=FaixaFronteira
      - FAIXA_FILE=Faixa_Fronteira_2021.shp
      - FAIXA_ESTADOS_OUTPUT=Faixa_Front_Estados
      - FAIXA_MUNICIPIOS_OUTPUT=Faixa_Front_Municipios
      
      # Variáveis para o notebook 09_UCPI.ipynb
      - UCPI_PATH=unidades
      - UCPI_FILE=unidades_conservacao.shp
      - UCPI_ESTADOS_OUTPUT=UCPI_Estados
      - UCPI_MUNICIPIOS_OUTPUT=UCPI_Municipios
      
      # Variáveis para o notebook 10_IntegracoesCAR.ipynb
      - INTEGRACAO_ANOS=2008,2021
      - INTEGRACAO_USO_PATH=Usos_ABC_Municipios
      - INTEGRACAO_TEMP_FOLDER=Temporarios
      - INTEGRACAO_OUTPUT=Potencial_Agropecuario
      
      # Variáveis para o notebook 11_AdequarParaBancoDados.ipynb
      - ADEQUAR_USO_PATH=${OUTPUT_PATH}/Usos_ABC_Municipios_CAR
      - ADEQUAR_DECL_PATH=${OUTPUT_PATH}/Decliv_UF_Municipios_CAR
      - ADEQUAR_EDAFO_PATH=${OUTPUT_PATH}/Aptd_Edafo_Municipios_CAR
      - ADEQUAR_ANOS=${ANOS_ABC}
      
      # Variáveis para o notebook 12_To_PostGis.ipynb
      - DB_HOST=postgres:5432
      - DB_NAME=lair
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_IMPORT_PATH=${OUTPUT_PATH}/Usos_ABC/Usos_ABC_Municipios/2021
      - DB_TABLE=2021
      - DB_SCHEMA=Usos_ABC
    command: python run_notebooks.py
    profiles:
      - batch

  # Serviço para execução interativa
  jupyter-interactive:
    build:
      context: .
      dockerfile: NotebooksDockerfile
    volumes:
      - ./:/home/jovyan/work
      - ./input:/home/jovyan/data/input
      - ./output:/home/jovyan/data/output
    environment:
      # Variáveis globais
      - INPUT_PATH=/home/jovyan/data/input
      - OUTPUT_PATH=/home/jovyan/data/output
      - PYTHONUNBUFFERED=1
      
      # Variáveis para o notebook 01_Download_CAR_estados.ipynb
      - SICAR_REPO=https://github.com/urbanogilson/SICAR
      - SICAR_EMAIL=sicar@sicar.com
      - ESTADOS_CAR=AC,AM,PA,AP,TO,MA,PI,CE,RN,PB,PE,AL,SE,BA,MG,ES,RJ,SP,PR,SC,RS,MS,MT,GO,DF,RO,RR
      - CAR_FOLDER=CAR
      - DEBUG=False
      
      # Variáveis para o notebook 02_UsosABC.ipynb
      - ORIGINAIS_PATH=originais_path
      - LIMITES_BUF=limites_buf
      - MUNICIPIOS_PATH=Municipios
      - MUNICIPIOS_FILE=BR_Municipios_2021.shp
      - ANOS_ABC=1985,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
      
      # Variáveis para o notebook 03_Declividade.ipynb
      - DECLIV_PATH=originais_path
      - TEMP_FOLDER=Temporarios
      - DECLIV_OUTPUT=Decliv_UF_Municipios
      - DECLIV_CAR_OUTPUT=Decliv_UF_Municipios_CAR
      
      # Variáveis para o notebook 04_CorrecaoEdafo.ipynb
      - APTIDAO_PATH=originais_path
      - APTIDAO_OUTPUT=Aptidao_Solo_Corrigida
      
      # Variáveis para o notebook 05_AptdEdafo.ipynb
      - APTIDAO_CORRIGIDA_PATH=Aptidao_Solo_Corrigida
      - APTIDAO_MUN_OUTPUT=Aptd_Edafo_Municipios
      - APTIDAO_CAR_OUTPUT=Aptd_Edafo_Municipios_CAR
      
      # Variáveis para o notebook 06_TerraIndigena.ipynb
      - TI_FILE=tis_poligonais.shp
      - TI_ESTADOS_OUTPUT=Terras_Indigenas_Estados
      - TI_MUNICIPIOS_OUTPUT=Terras_Indigenas_Municipios
      
      # Variáveis para o notebook 07_AmazoniaLegal.ipynb
      - AMZ_FILE=amazonia_legal.shp
      - AMZ_ESTADOS_OUTPUT=Amz_Legal_Estados
      - AMZ_MUNICIPIOS_OUTPUT=Amz_Legal_Municipios
      
      # Variáveis para o notebook 08_FaixaFronteira.ipynb
      - FAIXA_PATH=FaixaFronteira
      - FAIXA_FILE=Faixa_Fronteira_2021.shp
      - FAIXA_ESTADOS_OUTPUT=Faixa_Front_Estados
      - FAIXA_MUNICIPIOS_OUTPUT=Faixa_Front_Municipios
      
      # Variáveis para o notebook 09_UCPI.ipynb
      - UCPI_PATH=unidades
      - UCPI_FILE=unidades_conservacao.shp
      - UCPI_ESTADOS_OUTPUT=UCPI_Estados
      - UCPI_MUNICIPIOS_OUTPUT=UCPI_Municipios
      
      # Variáveis para o notebook 10_IntegracoesCAR.ipynb
      - INTEGRACAO_ANOS=2008,2021
      - INTEGRACAO_USO_PATH=Usos_ABC_Municipios
      - INTEGRACAO_TEMP_FOLDER=Temporarios
      - INTEGRACAO_OUTPUT=Potencial_Agropecuario
      
      # Variáveis para o notebook 11_AdequarParaBancoDados.ipynb
      - ADEQUAR_USO_PATH=${OUTPUT_PATH}/Usos_ABC_Municipios_CAR
      - ADEQUAR_DECL_PATH=${OUTPUT_PATH}/Decliv_UF_Municipios_CAR
      - ADEQUAR_EDAFO_PATH=${OUTPUT_PATH}/Aptd_Edafo_Municipios_CAR
      - ADEQUAR_ANOS=${ANOS_ABC}
      
      # Variáveis para o notebook 12_To_PostGis.ipynb
      - DB_HOST=postgres:5432
      - DB_NAME=lair
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_IMPORT_PATH=${OUTPUT_PATH}/Usos_ABC/Usos_ABC_Municipios/2021
      - DB_TABLE=2021
      - DB_SCHEMA=Usos_ABC
    ports:
      - "8888:8888"
    command: jupyter notebook --ip=0.0.0.0 --allow-root --NotebookApp.token=''
    profiles:
      - interactive

# Para executar em modo batch:
# docker-compose -f NotebooksCompose.yaml --profile batch up

# Para executar em modo interativo:
# docker-compose -f NotebooksCompose.yaml --profile interactive up