version: '3.8'

services:
  # Serviço principal para os scripts de integração temática
  integracao-tematica:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - ./config:/app/config
    environment:
      # Variáveis de ambiente para configuração dos scripts
      - INPUT_DIR=/data/inputs
      - OUTPUT_DIR=/data/outputs
      - TEMP_DIR=/data/temp
      # Se precisar conectar a um banco PostgreSQL externo, configure estas variáveis
      # - POSTGRES_HOST=seu_host_externo
      # - POSTGRES_PORT=5432
      # - POSTGRES_DB=seu_banco
      # - POSTGRES_USER=seu_usuario
      # - POSTGRES_PASSWORD=sua_senha
    # O contêiner será automaticamente removido após a conclusão
    # Uma vez que o script 00_Main.py termine, o contêiner será encerrado
    command: 00_Main.py
    # Para executar apenas em modo interativo, descomente a linha abaixo
    # command: bash

# Exemplos de uso:
#
# Para executar todos os scripts em sequência:
# docker-compose up --abort-on-container-exit
#
# Para executar apenas um script específico:
# docker-compose run --rm integracao-tematica 01_Download_CAR_estados.py
#
# Para acessar o shell do container:
# docker-compose run --rm integracao-tematica bash
#
# Para parar todos os serviços:
# docker-compose down 