version: "3.9"

services:
  jupyter:
    image: jupyter/scipy-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    environment:
      - NB_UID=1000
      - INPUT_PATH=/home/jovyan/data/input
      - OUTPUT_PATH=/home/jovyan/data/output