name: Build and Release CLI Executables

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --clean --onefile --name lair-postgis src/lair_postgis/cli.py

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/lair-postgis*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}